database-uri: "jdbc:postgresql://localhost/deepanddeeper?user=postgres&password=postgres"
weapons:
  - id: "cool_sword"
    name: "§7Basic §fSword"
    lore:
      - "The most basic of swords."
      - "Some more §btext§r."
    damage: 50.0
    # cooldown in seconds
    cooldown: 2.5
    material: "IRON_SWORD"
    price: 300
    classes:
      - "warrior"
  - id: "epic_sword"
    name: "§eEpic §fSword"
    lore:
      - "A slightly better sword."
    damage: 70.0
    cooldown: 2.4
    material: "DIAMOND_SWORD"
    price: 800
    classes:
      - "warrior"
  - id: "wizard_fireball"
    name: "§cFireball"
    lore:
      - "A fireball spell."
    damage: 100.0
    cooldown: 3.0
    material: "FIRE_CHARGE"
    price: 500
    classes:
      - wizard
enemies:
  - id: "skeleton"
    name: "Skeleton"
classes:
  - id: "warrior"
    name: "Warrior"
    health: 150.0
maps:
  - id: "cube"
    name: "Cube"
    schematic: "cube.schem"
    spawns:
      - x: 5.0
        y: 0.0
        z: 5.0
        yaw: 135.0
        pitch: 0.0
      - x: -5.0
        y: 0.0
        z: 5.0
        yaw: -135.0
        pitch: 0.0
      - x: 5.0
        y: 0.0
        z: -5.0
        yaw: 45.0
        pitch: 0.0
      - x: -5.0
        y: 0.0
        z: -5.0
        yaw: -45.0
        pitch: 0.0
