name: DeepAndDeeper
version: '${version}'
main: com.deepanddeeper.deepanddeeper.DeepAndDeeper
api-version: 1.20
commands:
  world:
    description: Prints out the current world of the player executing the command.
    usage: /world
