name: DeepAndDeeper
version: 0.1.0
main: com.deepanddeeper.deepanddeeper.DeepAndDeeper
api-version: 1.20

libraries:
  - org.postgresql:postgresql:42.6.0

commands:
  world:
    description: Prints out the current world of the player executing the command.
    usage: /world
  startgame:
    description: Starts the game.
    usage: /startgame
